### ISSUE TITLE
Add Calendar Code Program

### ISSUE THREAD

**Issue by MoveFl** [MoveFl/HacktoberFest-#3]

**Comment by vishal5251** [comment]
Assign this one to me.

**Comment by MoveFl** [comment]
> Assign this one to me.
OK

**Comment by vishal5251** [comment]
any discussion channel?

**Comment by MoveFl** [comment]
> any discussion channel?

Well this is not for my work just for hacktoberfest

**Comment by MoveFl** [comment]
@vishal5251 if you want to ask or discuss anything you may ask here bro!
